#!/bin/bash

sudo -u postgres psql <<EOPSQL
CREATE USER "$POSTGRES_USER" WITH PASSWORD "$POSTGRES_PWD";
CREATE DATABASE "$POSTGRES_DB";
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" to "$POSTGRES_USER";
EOPSQL
